Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 22

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

BlockLength:
  Exclude:
    - '*.gemspec'
    - 'lib/authify/api/controllers/*.rb'

AllCops:
  Exclude:
    - 'db/schema.rb'
