Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 22

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 9

Metrics/BlockLength:
  Max: 30
  Exclude:
    - '*.gemspec'
    - 'lib/authify/api/controllers/*.rb'
    - Rakefile
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'

AllCops:
  Exclude:
    - 'db/schema.rb'
